# ==========================================
# Application
# ==========================================

spring.application.name=medislot-provider-verification

# Server
server.port=8080


# ==========================================
# PostgreSQL Database
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/medislot
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / Hibernate
# ==========================================

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# Liquibase
# ==========================================

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml


# ==========================================
# Mail
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shaikhwasim3010@gmail.com
spring.mail.password=rarq bofc buzw rkxq

spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.auth=true


zoom.sdk.key=wnc2HxmDT5uoFFkqM3h0WA
zoom.sdk.secret=kyeVLgnJNYjImLLZN1Yw3CQJiJuLW3an